# Generated by Django 5.2 on 2025-04-06 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='Department ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Department name')),
                ('legacy_id', models.PositiveIntegerField(verbose_name='Department legacy ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='UnitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Unit group name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Unit group',
                'verbose_name_plural': 'Unit groups',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='Unit ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Unit name')),
                ('legacy_id', models.PositiveIntegerField(verbose_name='Unit legacy ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_types', to='units.department', verbose_name='Department')),
                ('dodo_is_api_account_tokens', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_types', to='accounts.accounttokens', verbose_name='Dodo IS API account tokens')),
                ('office_manager_account_cookies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_manager_units', to='accounts.accounttokens', verbose_name='Office manager account cookies')),
                ('shift_manager_account_cookies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_manager_units', to='accounts.accounttokens', verbose_name='Shift manager account cookies')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_types', to='units.unitgroup', verbose_name='Unit group')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
    ]
