# Generated by Django 5.2 on 2025-04-08 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='office_manager_account_cookies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_manager_units', to='accounts.accountcookies', verbose_name='Office manager account cookies'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='shift_manager_account_cookies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_manager_units', to='accounts.accountcookies', verbose_name='Shift manager account cookies'),
        ),
    ]
