# Generated by Django 5.2 on 2025-04-04 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Account ID')),
                ('login', models.CharField(max_length=255, verbose_name='Account login')),
                ('encrypted_password', models.CharField(max_length=255, verbose_name='Encrypted password')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='AccountCookies',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Account cookies ID')),
                ('encrypted_cookies', models.CharField(max_length=65535, verbose_name='Encrypted cookie')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Account cookies',
                'verbose_name_plural': 'Account cookies',
            },
        ),
        migrations.CreateModel(
            name='AccountTokens',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Account tokens ID')),
                ('encrypted_access_token', models.CharField(max_length=255, verbose_name='Encrypted access token')),
                ('encrypted_refresh_token', models.CharField(max_length=255, verbose_name='Encrypted refresh token')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Account token',
                'verbose_name_plural': 'Account tokens',
            },
        ),
    ]
