# Generated by Django 5.2 on 2025-04-05 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('telegram', '0002_alter_telegramchat_id_alter_telegramuser_id'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_routes', to='telegram.telegramchat', verbose_name='Telegram chat')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_routes', to='reports.reporttype', verbose_name='Report type')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_routes', to='units.unit', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Report route',
                'verbose_name_plural': 'Report routes',
                'constraints': [models.UniqueConstraint(fields=('chat', 'unit', 'report_type'), name='unique_report_route')],
            },
        ),
    ]
