# Generated by Django 5.2 on 2025-04-04 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False, verbose_name='Telegram ID')),
                ('title', models.CharField(max_length=255, verbose_name='Telegram title')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram username')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Telegram chat',
                'verbose_name_plural': 'Telegram chats',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False, verbose_name='Telegram ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram full name')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram username')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_roles.userrole', verbose_name='User role')),
            ],
            options={
                'verbose_name': 'Telegram user',
                'verbose_name_plural': 'Telegram users',
            },
        ),
    ]
